export const UPGRADES_LIST = [
  {
    name: 'Монетка',
    type: 'manual',
    price: 1,
    description: 'Дозволяє заробляти +1 монетку за клік',
    amount: 0,
    priceIncreaseMultiplier: 1.1435,
    isHidden: false,
  },
  {
    name: 'Селянин',
    type: 'auto',
    price: 100,
    description: 'Автоматично заробляє монетки раз на секунду',
    amount: 0,
    priceIncreaseMultiplier: 1.3665,
    multiplier: 1,
    isHidden: true,
  },
  {
    name: 'Лопата',
    type: 'auto',
    price: 700,
    description: 'Допомагає селянину заробляти більше монеток',
    amount: 0,
    priceIncreaseMultiplier: 1.455346,
    multiplier: 2,
    isHidden: true,
  },
  {
    name: 'Курка',
    type: 'auto',
    price: 900,
    description: 'Несе яєчка і заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.53345,
    multiplier: 2.44356,
    isHidden: true,
  },
  {
    name: 'Корова',
    type: 'auto',
    price: 2000,
    description: 'Допомагає селянину заробляти ще більше монеток',
    amount: 0,
    priceIncreaseMultiplier: 1.67868,
    multiplier: 3,
    isHidden: true,
  },
  {
    name: 'Ферма',
    type: 'auto',
    price: 10000,
    description: 'Приносить пшеницю і збільшує заробіток за секунду',
    amount: 0,
    priceIncreaseMultiplier: 1.8234,
    multiplier: 3.57567,
    isHidden: true,
  },
  {
    name: 'Млин',
    type: 'auto',
    price: 50000,
    description: 'Меле пшеницю та заробляє щосекунди монетки',
    amount: 0,
    priceIncreaseMultiplier: 2,
    multiplier: 3.7764,
    isHidden: true,
  },
  {
    name: 'Корчма',
    type: 'auto',
    price: 500000,
    description: 'Заробляє монетки щосекунди, але зменшує ефективність селян',
    amount: 0,
    priceIncreaseMultiplier: 1.45234,
    multiplier: 3.9674,
    isHidden: true,
  },
  {
    name: 'Церква',
    type: 'auto',
    price: 1500000,
    description: 'Заробляєм монетки, але зменшує ефективність корчми',
    amount: 0,
    priceIncreaseMultiplier: 1.7862,
    multiplier: 4.23474,
    isHidden: true,
  },
  {
    name: 'Базар',
    type: 'auto',
    price: 3000000,
    description: 'Заробляє монетки щосекунди',
    amount: 0,
    priceIncreaseMultiplier: 1.853453,
    multiplier: 4.7345345,
    isHidden: true,
  },
  {
    name: 'Мольфар',
    type: 'auto',
    price: 5000000,
    description: 'Заробляєм монетки, але зменшує ефективність корчми',
    amount: 0,
    priceIncreaseMultiplier: 1.945,
    multiplier: 5.436,
    isHidden: true,
  },
  {
    name: 'Кузня',
    type: 'auto',
    price: 9000000,
    description: 'Заробляєм монетки, але зменшує ефективність корчми',
    amount: 0,
    priceIncreaseMultiplier: 2.3456,
    multiplier: 6,
    isHidden: true,
  },
  {
    name: 'Мануфактура',
    type: 'auto',
    price: 100000000,
    description: 'Заробляєм монетки, але зменшує ефективність корчми',
    amount: 0,
    priceIncreaseMultiplier: 2.845435,
    multiplier: 6.34563,
    isHidden: true,
  },
];