export const UPGRADES_LIST = [
  {
    name: 'Заробити самостійно',
    type: 'manual',
    price: 1,
    description: 'Дозволяє заробляти монетки кліками',
    amount: 0,
    priceIncreaseMultiplier: 1.1,
    isHidden: false,
    multiplier: 1,
    image: 'coin.svg',
  },
  {
    name: 'Селянин',
    type: 'auto',
    price: 100,
    description: 'Автоматично заробляє монетки раз на секунду',
    amount: 0,
    priceIncreaseMultiplier: 1.2,
    multiplier: 1,
    isHidden: true,
    image: 'villager.png',
  },
  {
    name: 'Лопата',
    type: 'manual',
    price: 200,
    description: 'Допомагає заробляти більше монеток за клік',
    amount: 0,
    priceIncreaseMultiplier: 1.3,
    multiplier: 3,
    isHidden: true,
  },
  {
    name: 'Курка',
    type: 'auto',
    price: 300,
    description: 'Несе яєчка і заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.4,
    multiplier: 3,
    isHidden: true,
    image: 'chicken.png',
  },
  {
    name: 'Свиня',
    type: 'auto',
    price: 500,
    description: 'Шукає жолуді і заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.5,
    multiplier: 8,
    isHidden: true,
    image: 'pig.png',
  },
  {
    name: 'Корова',
    type: 'auto',
    price: 1000,
    description: 'Приносить молочко і збільшує заробіток за секунду',
    amount: 0,
    priceIncreaseMultiplier: 1.6,
    multiplier: 13,
    isHidden: true,
    image: 'cow.png',
  },
  {
    name: 'Фермер',
    type: 'auto',
    price: 2000,
    description: 'Вирощує пшеницю та заробляє щосекунди монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.7,
    multiplier: 20,
    isHidden: true,
    image: 'farmer.png',
  },
  {
    name: 'Лісоруб',
    type: 'auto',
    price: 3250,
    description: 'Рубає дерева і заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.8,
    multiplier: 35,
    isHidden: true,
    image: 'lumberjack.png',
  },
  {
    name: 'Шахтар',
    type: 'auto',
    price: 5500,
    description: 'Здобуває руду і заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 1.9,
    multiplier: 50,
    isHidden: true,
    image: 'miner.png',
  },
  {
    name: 'Крамар',
    type: 'auto',
    price: 8000,
    description: 'Заробляє монетки щосекунди',
    amount: 0,
    priceIncreaseMultiplier: 2,
    multiplier: 80,
    isHidden: true,
    image: 'merchant.png',
  },
  {
    name: 'Коваль',
    type: 'auto',
    price: 10000,
    description: 'Кує залізо та заробляє монетки',
    amount: 0,
    priceIncreaseMultiplier: 2.1,
    multiplier: 100,
    isHidden: true,
    image: 'blacksmith.png',
  },
  {
    name: 'Священник',
    type: 'auto',
    price: 20000,
    description: 'Заробляєм монетки, але зменшує ефективність корчми',
    amount: 0,
    priceIncreaseMultiplier: 2.2,
    multiplier: 200,
    isHidden: true,
  },
  {
    name: 'Мольфар',
    type: 'auto',
    price: 100000,
    description: 'Заробляєм монетки',
    amount: 0,
    priceIncreaseMultiplier: 2.3,
    multiplier: 1000,
    isHidden: true,
  },
];